language: ruby
rvm:
  - 2.5.3
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
  - bundle exec rake test

services:
  - docker

# make use of vm's
sudo: 'required'


deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
